# Generated by Django 2.2.1 on 2019-05-09 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_name', models.CharField(max_length=50)),
                ('cocktail_image', models.ImageField(blank=True, null=True, upload_to='cocktail_images/')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('cocktail_info', models.CharField(blank=True, max_length=200, null=True)),
                ('cocktail_steps', models.CharField(blank=True, max_length=1000, null=True)),
                ('virgin', models.BooleanField(null=True)),
                ('cocktail_type', models.CharField(choices=[('WHISKEY', 'Whiskey'), ('VODKA', 'Vodka'), ('TEQUILA', 'Tequila'), ('GIN', 'Gin'), ('VIRGIN', 'Virgin')], max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
